# Numpy

**python의 속도문제를 해결하기 위한 방법**
- computing power
- compiler
- glue language 
- algorithm / datastructure

--> 계산관련 속도 빠르게 만든 애 : numpy

**numpy를 쓰는 이유**
- 속도가 빠르다 (c로 만들어짐,효율적인 데이터구조(호모지니어스, 백터라이제이션))
- 편하고 쉽다  

**vectorization = array programming**  
- 여러개의 데이터를 하나의 묶음으로 처리함
- for문을 쓰지 않는다  
- 계산 빨라짐
- 항상 빨라지진 않음. 작은 프로그램에서는 오히려 느릴 수 있다.

- 1차원 : vector : 방향이 없다
- 2차원 : matrix
- n차원 : n차원 tensor

In [1]:
import numpy as np

In [3]:
dir(np)
#파이썬은 명시적인 상수가 없지만, 대문자로 쓰면 상수로 씀

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [4]:
#인스턴스화하지 않고 다른 함수의 힘을 빌려 인스턴스화 하는 것 = 팩토리 메소드
#--> 디자인패턴 방법
#호모지니어스함.
#호모찌니어스의 장젖ㅁ? 다음데이터타입ㅂ이 뭐가 올 지 체크할필요가 없ㅂ다.
# == 속도가 빠르다
#데이터가 한개 이상
#mutable
a = np.array((1,2))

In [5]:
a

array([1, 2])

In [6]:
type(a) 
#n차원 array
#앞에 nd가 붙으면 numpy로 만들었구나 알수 있다

numpy.ndarray

In [7]:
a = np.array([[1,2],[3,4]]) #2차원

In [10]:
a

array([[1, 2],
       [3, 4]])

In [5]:
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]]) #3차원

In [6]:
a #삼차원은 공백이 나옴
#공백이 나오면 데이터가 겹쳐져 있구나 알 수 이씀

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [22]:
type(a) #클래스다 = 인스턴스화할 수 있다

numpy.ndarray

In [11]:
n = np.ndarray(0)

In [12]:
print(n)

[]


In [25]:
a = np.array(['1',2,3])

In [29]:
a
#호모지니어스하기 때문에 스트링으로 다 바꿔줘버림
#dtype 

array(['1', '2', '3'], dtype='<U1')

In [13]:
n = np.ndarray([0,'1'])
#얜 에러나
#-> 팩토리메소드를 쓰면 에러도 안나고 편하다~

TypeError: 'str' object cannot be interpreted as an integer

**인스턴스화 방법 세가지**
- 클래스이용해서 인스턴스화
- 리터럴
- 팩토리메소드이용 

In [31]:
vars(a)  #__dict가 정의가 안돼있음. 값을 한개만 가짐

TypeError: vars() argument must have __dict__ attribute

In [7]:
a = np.array([[1,2],[3,4]])

In [16]:
print(a.ndim) #몇차원인지 알려줌
print(a.shape)

2
(2, 2)


In [38]:
a.shape #몇행 몇열인지 알려줌

(2, 2)

In [40]:
a.flags
#c방식이냐, 포트란방식이냐 보여줌
#c는 옆으로, 포트란ㅇ은 밑으로 저장함


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [43]:
a.size #원소의 갯수

4

In [45]:
a.itemsize #각 애가 몇비트인가

8

In [47]:
a.dtype  #데이터 타입

dtype('int64')

In [49]:
x = [1,2,3,4]
y = [2,3,4,5]

In [51]:
x+y  #파이썬은 그냥 옆에 붙여주지만

[1, 2, 3, 4, 2, 3, 4, 5]

In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [57]:
a+b  #넘파이로 만들면 더해준다!!

array([[2, 4],
       [6, 8]])

In [58]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
#이렇게 계산하는 법을 엘리멘트 머라고 ? 

In [59]:
[a+b for a,b in zip(x,y)]  # 파이썬으로 더하기하는법

[3, 5, 7, 9]

In [61]:
a.T  #행과 열을 바꾸는 법

array([[1, 3],
       [2, 4]])

In [9]:
a.strides 
#최대공약수로 나눠
#두개가 한 행을 가진다
#4개짜리니까 2행 2열이다
#실제로는 한행이지만 stride를 이용해서 자유롭게 바꾸기 가능

(16, 8)

**numpy가 쉬운 이유**
- Data Type : 작은 범위까지 다 지원해준다 = 지정해주기만 하면 알아서 다 처리해준다


In [70]:
a = np.array([[1,2],[3,4]], dtype='u1')  #데이터타입을 하나 찍어서 만들어줄 수 있음

In [72]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [74]:
np.sctypeDict #타입이 이렇게 많다~

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.int64,
 'q': numpy.int64,
 9: numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 10: numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,


In [75]:
len(np.sctypeDict)

158

**언..더..바..**
1. 앞에 _ 붙을때 : 갈래상 private
2. _ 하나 붙을 때 : from * 할때 임포트가 안됨
3. 앞에 _ 두개 붙을 때 : 맹글링
4. 앞에 두개 뒤에 두개 : 매직메소드 or 스페셜 메소드
5. 갈래상 필요없는 변수 이름
6. 맨 마지막 결과를 담고 있음
7. _(a) : 다국어 처리 할 때
8. 이름 뒤에 _붙을 때 : 갈래상 파이썬 이름이랑 똑같을때 구분하기위해 언더바처리해줌

**stride 개념**  
꼭알아야돼1!  
특정값 찾을때 스트라이드 사용하면 아주 빨리 찾을 수 있음  

**axis개념**  
행끼리 계산하는건 axis = 0 (0자리 가리면 계산 후 행렬나옴)   
열끼리 계산하는건 axis = 1 (1자리 가리면 ") 
--> 아주 속도가 빠르다 (스트라이드가있기때문)


In [3]:
a = np.arange(10)  
#특정 범위만큼 값을 만들어줒ㅁ
#파이썬의 range랑 같음

In [78]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a.reshape(2,5)
#reshape : 모양을 바꿀수있음

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
a
#뮤터블이면 바뀌어야하는데.. ?
#뮤터블함수의 결과는 세가지.
#1. 자기자신은 바뀌지만 리턴값이 none
#2. 리턴값있지만 안바뀜
#3. 리턴값도있고 바뀜 (pop)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = a.reshape(2,5)
#reshape은 카피개념이라 재할당해야해

In [5]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
a.sum(0)  #파라메터에 axis들어감. 안집어넣으면 전체 다 더해줌

array([ 5,  7,  9, 11, 13])

In [13]:
a.min(1)

array([0, 5])

In [19]:
a.strides

(40, 8)

In [20]:
a.size

10

In [21]:
%time sum(range(1000000000))

CPU times: user 14.1 s, sys: 92.5 ms, total: 14.2 s
Wall time: 14.2 s


499999999500000000

In [22]:
%time np.sum(np.arange(1000000000))  
#훠어어어얼씬빠르다

CPU times: user 2.44 s, sys: 1.94 s, total: 4.38 s
Wall time: 4.4 s


499999999500000000

In [6]:
a = np.zeros((3,4))  #0으로만들기
b = np.ones((3,3))  #1로만들기
c = np.full((3,2),6)

In [7]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
c

array([[6, 6],
       [6, 6],
       [6, 6]])

In [26]:
d = np.ones_like(a)  #_like : shape만 똑같은 애를 1로 만들어줌. 아주 자주쓴다!

In [24]:
d = np.zeros_like(a)

In [27]:
d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
b = np.eye(3)  #단위행렬

In [13]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
c = np.identity(3) #얘도 단위행렬 만드는 애. eye보다 옵션이 적고 빠르게 만들 때사용



In [15]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#상삼각행렬, 하상각행렬 등등 이름있는 행렬들 다 만들 수 있음
b = np.triu((3,3))

In [30]:
b

array([[3, 3],
       [0, 3]])

In [19]:
b.T  #전치행렬

array([[3, 0],
       [3, 3]])

In [39]:
d = np.linspace(0,100,5)

In [40]:
d

array([  0.,  25.,  50.,  75., 100.])

In [37]:
e = np.logspace(1,100,5)

In [38]:
e

array([1.00000000e+001, 5.62341325e+025, 3.16227766e+050, 1.77827941e+075,
       1.00000000e+100])

In [24]:
e = np.empty((4,2)) #초깃값 만들어줌

In [25]:
e

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**이제 특정 값을 뽑아내보자!**
- indexing, slicing

In [2]:
a = np.arange(10).reshape(2,5)

In [3]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
a[1][3]  #파이썬방식

8

In [29]:
a[1,3]  #numpy방식

8

In [31]:
a[:,3]  #특정열, 특정행 뽑아줌

array([3, 8])

In [5]:
a = np.arange(27).reshape(3,3,3)

In [6]:
a 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
a[1,:]  #괄호 안에 두개빢에 없어도 지가 알아서 다 가져와 줌

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [24]:
a[:2,0:2,]  
#콤마는 축을 나눠주는 것. (축 : 대괄호)
#첫번째: 뭉탱이 
#두번쨰 : 행 
#세법ㄴ째 :열
#:2 --> 0부터1뭉탱이까지
#0:2 --> 0부터 1행까지
#지정해주지 않으면 모든 열을 뽑는다.

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [25]:
a[1,...]  #... : 전부 다 

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [29]:
a[:,:,1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [30]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
a[(a>3) & (a<8)] #조건 붙이기 가능

array([4, 5, 6, 7])

In [57]:
#마스킹 기법.= 트루인애들만 뽀ㅃ아낼 수 있음
a = np.arange(5)
a[[True,True,True,True,False]]

array([0, 1, 2, 3])

In [41]:
a>2

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Fancy indexing

In [37]:
#fancy indexing
#행 뽑을때엄청쉽ㄱ베 뽑을수있음
a = np.arange(25).reshape(5,5)

In [38]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
a[[1,3]]
#행 뽑는 법
#1행 , 3행

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [42]:
a[[1,2,4],[2,3,4]]  
#행과 열 뽑는 법
#1행의 2열, 2행의 3열, 4행의 4열

array([ 7, 13, 24])

In [72]:
b = np.nditer(a)
#numpy도 iterator개념이 있어~ 중요한건 for쓰면 싸대기맞아. vector개념모르는거임 ㅋㅋ

In [77]:
next(b),.=

array(1)

In [78]:
def add_(a,b):
    return a+b

In [79]:
x = np.arange(5)
y = np.arange(5)

In [80]:
add_(x,y)

array([0, 2, 4, 6, 8])

In [81]:
x

array([0, 1, 2, 3, 4])

In [82]:
x*3

array([ 0,  3,  6,  9, 12])

In [84]:
3 + np.arange(10)
#broadcasting
#-> 간단할 경우 크기를 자동으로 맞ㅈ춰줌

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

**numpy 쉬운이유**
- indexing/slicing( 값 뽑아내기 쉬움)
- 브로드캐스팅
- ufunc(universial=보편적인)
- 마스킹
- 조건

In [85]:
abs([-1,2,3])
#여러개 안됨

TypeError: bad operand type for abs(): 'list'

In [86]:
#shift+tab -> ufunc 타입. = 여러개 계산가능
np.abs([-1,3,2])
#넘파이는 지원해줌

array([1, 3, 2])

In [87]:
#shift+tab -> ufunc 타입. = 여러개 계산가능
np.ceil([2.3,2,3,4,1.4])

array([3., 2., 3., 4., 2.])

In [88]:
np.info(np.ceil) #numpy에서 설명 보는 법

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [89]:
from scipy.special import factorial

In [93]:
#scipy에 웬만한거 다 만들어ㅕㅈ있어.
#빨리 찾는게 핵심이야
factorial([3,4,5])

array([  6.,  24., 120.])

In [96]:
#scipy도 넘파이로 만들었기 때문에 넘파이에서 가져와도 보임
np.info(factorial)

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


In [99]:
#uiversial function은 shift+tab으로 안보이고 np.info()해서 봐야한다
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x1084bd550>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +SKIP
  

In [100]:
b = np.arange(10)

In [102]:
np.where(b>5, 0, 1)
#5보다 크면 0 으로 밥꿔라, 아니면 1로 바꿔라

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [103]:
b = np.arange(5,10)

In [104]:
np.where(b>5)  #조건에 맞는 인덱스 뽑아줌

(array([1, 2, 3, 4]),)

In [105]:
np.argmax(b) #제일 큰 수의 인덱스 뽑아ㅜㅈㅁ

4

In [106]:
np.argmin(b) #제일 작은애의 인덱스

0

In [107]:
b.argmin()

0

In [108]:
from numpy import pi

In [109]:
from math import pi as mpi

In [110]:
pi

3.141592653589793

In [111]:
mpi

3.141592653589793

In [112]:
pi == mpi  #python에 있는 패키지랑 numpy랑 똑같음
#간혹 이렇게 똑같은 애들도 있음
#굳이 왜 새로만드냐 그러면 ?
#math를 한번더 임포트하면 메모리상에 한번 더 올라가니까 비효율적이다


True

In [113]:
pi is mpi
#다른 메모리에 있으니까 is는 달라~

False

In [115]:
np.nan  

nan

In [117]:
float('nan')

nan

In [120]:
np.nan == float('nan')

False

In [122]:
t = float('nan')  #이런건 어쩔 수 없이 외워야한다

In [123]:
np.set_printoptions(threshold=t)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [125]:
np.newaxis == None #이런건 어쩔 수 없이 외워야한다

True

In [127]:
a = np.arange(10).reshape(2,5)

In [129]:
b = a

In [130]:
a[0][0] = 100

In [131]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [132]:
c = b.copy()

In [133]:
c

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [134]:
b[0][0] = -100

In [135]:
b

array([[-100,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [136]:
c
#python에서는 copy하면 swallow copy였음
#np에서는 copy하면 deep copy임

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [137]:
c = b.view() 
#swallow copy는 view임

In [138]:
b[0][0] = 2109

In [139]:
c

array([[2109,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [140]:
#카피를 해야하는 이유? 원본을 보관하기 위해!