In [1]:
import numpy as npㅂ

In [6]:
#np.info()말고 또 정보를 알 수 있는 법
#하나하나 구글링하지 않아도 info랑 lookfor를 통해 사용뻡을 알 수 있다.
np.lookfor('create')

Search results for 'create'
---------------------------
numpy.array
    Create an array.
numpy.dtype
    Create a data type object.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.nested_iters
    Create nditers for use in nested loops
numpy.bytes0.hex
    B.hex() -> string
numpy.byte.__new__
    Create and return a new object.  See help(type) for accurate signature.
numpy.bool8.__new__
    Create and return a new object.  See help(type) for accurate signature.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.matlib.rand
    Return a matrix of random values with given shape.
numpy.int0.__new__
    Create and return a new object.  See help(type) for accurate signature.
numpy

In [7]:
a = np.array(100)

In [8]:
a

array(100)

In [9]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a = np.arange(27)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [14]:
a.shape #1차

(27,)

In [16]:
a.reshape(3,9)  #reshape은 mutable function이아닉때문에 자기 자신이 안바뀜

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [19]:
b = a.reshape(3,9)

In [21]:
b[0,0] = 100

In [22]:
a 
#a도 변해버림. 참조를 같이 갖ㅈ고잇음.
#이래서 카피를 써야 한다
#이동네 카피는 딥카피~

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26])

In [23]:
b = a.reshape(3,9).copy()
#이렇게 써서 같이 바뀌는거 막아야한다

In [25]:
b = a.reshape(3,-1)  
#-1은 automatic이라는 뜻. -1이 자동적으로 9로 바뀜
#reshape을 다 계산해 줄 ㅍ ㅣㄹ요 없음.
#한쪽에만 쓸 수 있음

In [26]:
b

array([[100,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26]])

In [30]:

#reshape이랑 비슷한 애 
#resize는 mutable function이기때문에 자기자신도 변함
#상황에따라ㅓ서 쓰삼
a = np.arange(27)
a.resize((3,9))

In [31]:
a


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [34]:
#상황에따라ㅓ서 쓰삼
a = np.arange(27)

In [35]:
a.resize((3,10))

In [36]:
a 
#resize는 크기를 다르게 설정해줘도 에러 안나. 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26,  0,  0,  0]])

In [39]:
#split : 모양을 쪼개주는 애
#종류 세가지
#hsplit
#split
#vsplit

In [46]:
a = np.arange(27)

In [47]:
a = a.reshape(3,9)

In [48]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [53]:
np.split(a, (1,2)) 
#(1,2) -> 0에서 1까지, 1에서 2까지, 2에서 끝까지 짤라줌

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [54]:
np.split(a, (2,2))   #0에서 2까지, 2에서 2깢지(비어있음), 2에서 끝까지

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int64),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [56]:
np.split(a, (2,5))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int64)]

In [57]:
np.split(a, (-2,5))
#기준이 0이다. (에러는안남)

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int64)]

In [58]:
np.split(a, (5,5), axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int64),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [59]:
np.hsplit(a, (5,))
#이거 쓰면 구분선 없애고 짜를 수 있어

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [60]:
np.vsplit(a, (2,))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [61]:
#결국 split만 알고있으면 돼.
#split (axis=1)이 hsplit
#split (axix=0)이 vsplit

In [62]:
b = np.arange(5)

In [63]:
c = np.arange(5,10)

In [65]:
np.stack((b,c)) #기본이 axix=0

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
np.stack((b,c), 1) 

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [67]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
#언더바삼총사 ( r_, c_, s_)
np.r_[b,c]
# r_ : hstack이랑 똑같음. 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.c_[b,c]
#c_ : column

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [71]:
[1,2,3,4,5,][slice(1,5)]

[2, 3, 4, 5]

In [72]:
np.arange(10)[np.s_[1]]
#s_ : slice객체 만들어주는애

1

In [73]:
np.column_stack([b,c])
#붙이는 방법

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [78]:
# --> 붙이는애들, 쪼개는애들 기억하고 있어야해 
#데이터 붙일때 씀

In [79]:
a = np.arange(6)  

In [80]:
a
#이건 일차원. 
#2차원으로 바꾸고 싶다! 하면?

array([0, 1, 2, 3, 4, 5])

In [77]:
a.reshape(6,1)
#이렇게 말고, 괄호만 추가시키고 싶어

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [81]:
a[np.newaxis]
#np.newaxis는 새로운 축을 만드는 애!

array([[0, 1, 2, 3, 4, 5]])

In [85]:
a = a.reshape(2,3)

In [86]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [87]:
a[np.newaxis] #3차원으로

array([[[0, 1, 2],
        [3, 4, 5]]])

In [88]:
a[:,np.newaxis] 

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [89]:
a[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [90]:
a = np.arange(6)

In [91]:
a[:, np.newaxis]
#각각의 차원을 만들어줄 수 있다! 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [94]:
np.expand_dims(a,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [97]:
np.expand_dims(a,2) 
#3차원으로 증가 못시켜줌, 
#차원을 하나씩밖에 증가 못시켜주는 애

/Users/jung-yeongseo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [98]:
a = np.arange(27).reshape(3,3,3)

In [99]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
np.swapaxes(a, 0,1)
#축바꿔줌

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])

In [102]:
np.moveaxis(a, 0,2)
#축 이동시켜줌

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

In [93]:
#모양을 자유자재로 바꿀줄 알아야해.
#행렬은 shape이 같아야 연산이 가능하기 때문

In [107]:
#numpy에서는 사용자 데이터타입을 만들 수 있다! 
#결국은 얘를 하기위해 지금까지 한것 ㅋㅋ
#사용자 데이터타입 : 리스트형태임
#정형화된 데이터를 만들고 싶을때 사용한다.

In [133]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [134]:
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [110]:
from collections import namedtuple

In [111]:
Address = namedtuple('Address', ('name', 'age', 'weight'))

In [114]:
a1 = Address('Rex', 27, 81.0)

In [115]:
a1.name

'Rex'

In [116]:
dir(a1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'age',
 'count',
 'index',
 'name',
 'weight']

In [117]:
b = (1,)

In [118]:
dir(b)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [119]:
a1[0]
#튜플이기때문에 인덱스도 가능하다

'Rex'

In [120]:
a1['name'] #key로는 접근X

TypeError: tuple indices must be integers or slices, not str

In [121]:
#numpy는 딕셔너리처럼 key로 접근가능함
#즉, 행으로도 열로도 접근 가능하다
#index하면 row로가져옴
#key하면 column가져옴

In [131]:
x[1]

('Fido', 3, 27.)

In [132]:
x['age']

array([9, 3], dtype=int32)

In [128]:
x.age

AttributeError: 'numpy.ndarray' object has no attribute 'age'

In [127]:
'name' in dir(x)  
#--> 어트리뷰트 방식으로는 접근 못한다!
#namedtuple에서는 키방식으로 접근 못했었음.
#각각 사용법이 조금씩 달라

False